# Generated by Django 4.0.4 on 2022-05-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_attendance_delete_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
