# Generated by Django 4.0.4 on 2022-05-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_marks_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='ComputerMarks',
            new_name='LanguageMakrs',
        ),
    ]
