# Generated by Django 4.0.4 on 2022-05-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_marks_id_alter_marks_studentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='LanguageMakrs',
            new_name='LanguageMarks',
        ),
    ]
